import { AdminActionForm } from "@/components/admin-action-form";
import { AdminCampaignRevoke } from "@/components/admin-campaign-revoke";
import { AdminHeading } from "@/components/admin-heading";
import { pressayJSON } from "@/lib/pressay-api";

type Campaign = { id: string; public_id: string; kind: string; code_hint: string | null; plan_code: string | null; duration_days: number | null; discount_percent: number | null; discount_amount: number | null; max_redemptions: number; redemptions: number; status: string; expires_at: string | null };
export default async function AdminCampaignsPage() {
  const { data } = await pressayJSON<{ campaigns: Campaign[] }>("admin/campaigns");
  return <>
    <AdminHeading eyebrow="ACCESS / PROMOTIONS" title="Campagnes" detail="Liens et codes hashés, limites de consommation, expiration et révocation indépendante des droits déjà accordés." />
    <section className="admin-actions-section admin-actions-grid">
      <AdminActionForm endpoint="/api/pressay/admin/campaigns" title="Créer un accès gratuit" description="Le secret brut ne sera affiché qu’une fois." submitLabel="Créer le code" fields={[{ name: "kind", label: "", type: "hidden", value: "access_grant" }, { name: "delivery", label: "Format", type: "select", options: [{ label: "Code", value: "code" }, { label: "Lien secret", value: "link" }] }, { name: "plan", label: "Droit", type: "select", options: [{ label: "Pro BYOK", value: "pro_byok" }, { label: "Lifetime (owner + MFA)", value: "lifetime_byok" }] }, { name: "durationDays", label: "Durée (1–365)", type: "number", value: 30 }, { name: "maxRedemptions", label: "Utilisations max", type: "number", value: 1 }, { name: "restrictedEmail", label: "Email limité (optionnel)", type: "email" }, { name: "expiresAt", label: "Expiration", type: "datetime-local" }, { name: "internalNote", label: "Note interne" }, { name: "reason", label: "Motif d’audit", required: true }]} />
      <AdminActionForm endpoint="/api/pressay/admin/campaigns" title="Créer une réduction Stripe" description="Coupon à usage unique, généré côté serveur dans Stripe." submitLabel="Créer la promotion" fields={[{ name: "kind", label: "", type: "hidden", value: "stripe_discount" }, { name: "delivery", label: "", type: "hidden", value: "code" }, { name: "discountPercent", label: "Réduction en %", type: "number", value: 20 }, { name: "maxRedemptions", label: "Utilisations max", type: "number", value: 1 }, { name: "expiresAt", label: "Expiration", type: "datetime-local" }, { name: "internalNote", label: "Note interne" }, { name: "reason", label: "Motif d’audit", required: true }]} />
    </section>
    <div className="admin-table-wrap"><table className="admin-table admin-campaigns-table"><thead><tr><th>Campagne</th><th>Type</th><th>Avantage</th><th>Usage</th><th>Statut</th><th>Expiration</th><th>Action</th></tr></thead><tbody>{data?.campaigns.map((campaign) => <tr key={campaign.id}><td><strong>{campaign.public_id}</strong><small>{campaign.code_hint ? `…${campaign.code_hint}` : "Lien secret"}</small></td><td>{campaign.kind}</td><td>{campaign.plan_code ? `${campaign.plan_code} · ${campaign.duration_days ?? "∞"} j` : campaign.discount_percent ? `−${campaign.discount_percent} %` : `−${Number(campaign.discount_amount) / 100} €`}</td><td>{campaign.redemptions}/{campaign.max_redemptions}</td><td><span className="admin-pill">{campaign.status}</span></td><td>{campaign.expires_at ? date(campaign.expires_at) : "Aucune"}</td><td>{campaign.status === "active" ? <AdminCampaignRevoke campaignID={campaign.id} publicID={campaign.public_id} /> : "—"}</td></tr>)}</tbody></table></div>
  </>;
}
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(value)); }
